name: arqueotimes_application
description: The ArqueoTimes app.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  html: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.9.2"

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/icons/icon.png
    
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"